spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
#  security:
#    user:
#      name: admin
#      password: pwd
server:
  port: 9090

logging.level.org.zalando.logbook: TRACE
logbook:
  include:
    - "**/users"
    - "**/findAll"
    - "**/findUsers"
