server:
  port: 9070

spring:
  application:
    name: spring-thread-example
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        healthCheckPath: /actuator/health
#  security:
#    user:
#      name: admin
#      password: pwd

logging.level.org.zalando.logbook: TRACE
logbook:
  include:
    - "**/users"
    - "**/findAll"
    - "**/findUsers"

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      externalService:
        baseConfig: default
        waitDurationInOpenState: 20s
        failureRateThreshold: 50